export const LOGINUSER = 'LOGINUSER';
export const LOGERROR = 'LOGERROR';
export const LOGOUTUSER = 'LOGOUTUSER';

export const FETCHCLIENTS = 'FETCHCLIENTS';
export const SEARCHCLIENT = 'SEARCHCLIENT';